name: Assume AWS IAM Role with Federated Authentication
description: An action which assumes an AWS IAM Role using Open ID Connect. **Experimental**
author: Josh Feierman
inputs:
  aws_iam_role_arn:
    description: The ARN of the AWS IAM Role to assume.
    required: true
  aws_default_region:
    description: The default region to use when consuming the credentials. Equivalent to the CLI's AWS_DEFAULT_REGION environment variable.
    required: true
    default: us-east-1
runs:
  using: composite
  steps:
    - name: Assume IAM Role
      shell: bash
      run: |
        export AWS_ROLE_ARN=${{ iam_role_arn }}
        export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
        export AWS_DEFAULT_REGION=${{ aws_default_region }}

        echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
        echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
        echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE